# Generated by Django 5.1.3 on 2024-11-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocppconnection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag', models.CharField(max_length=100, unique=True, verbose_name='Identificador')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('carregando', 'Carregando'), ('ocupado', 'Ocupado')], default='disponivel', max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.DeleteModel(
            name='Charger',
        ),
    ]
